const productsData = {
    "products": [
      {
        "id": "matin-heritage-top-bb",
        "name": "MATIN HERITAGE TOP",
        "color": "BLACK",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩68,00",
        "discountPrice": "₩61,200",
        "image": "./images/MK2400TS005MBB.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=5088&cate_no=27&display_group=1",
        "smsBody": "MATIN HERITAGE TOP (BLACK/FREE) 구매 문의합니다.",
        "ordering": 101
      },
      {
        "id": "matin-kim-logo-coating-jumper-bb",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "BLACK",
        "size": "FREE",
        "quantity": 0,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2500JP002VBB.jpg",
        "isSoldOut": true,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=5038&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(BLACK/FREE) 구매 문의합니다.",
        "ordering": 102
      },
      {
        "id": "matin-kim-logo-coating-jumper-be",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "BEIGE",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400JP002MBE.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3341&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(BEIGE/FREE) 구매 문의합니다.",
        "ordering": 103
      },
      {
        "id": "matin-kim-logo-coating-jumper-gy",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "GREY",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400JP002MGY.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3339&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(GREY/FREE) 구매 문의합니다.",
        "ordering": 104
      },
      {
        "id": "matin-kim-logo-coating-jumper-iv",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "IVORY",
        "size": "FREE",
        "quantity": 3,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400JP002MIV.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=5039&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(IVORY/FREE) 구매 문의합니다.",
        "ordering": 105
      },
      {
        "id": "matin-kim-logo-coating-jumper-na",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "NAVY",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400JP002MNA.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3340&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(NAVY/FREE) 구매 문의합니다.",
        "ordering": 106
      },
      {
        "id": "matin-kim-logo-coating-jumper-pk",
        "name": "MATIN KIM LOGO COATING JUMPER",
        "color": "PINK",
        "size": "FREE",
        "quantity": 5,
        "originalPrice": "₩162,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400JP002M.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=5125&cate_no=26&display_group=1",
        "smsBody": "MATIN KIM LOGO COATING JUMPER(PINK/FREE) 구매 문의합니다.",
        "ordering": 107
      },
      {
        "id": "accordion-wallet-sv",
        "name": "ACCORDION WALLET",
        "color": "SILVER",
        "size": "FREE",
        "quantity": 3,
        "originalPrice": "₩88,000",
        "discountPrice": "₩79,200",
        "image": "./images/MK2400WL001MSV.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3029&cate_no=167&display_group=1",
        "smsBody": "ACCORDION WALLET(SILVER/FREE) 구매 문의합니다.",
        "ordering": 108
      },
      {
        "id": "accordion-wallet-wh",
        "name": "ACCORDION WALLET",
        "color": "WHITE",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩88,000",
        "discountPrice": "₩79,200",
        "image": "./images/MK2400WL001MWH.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=2163&cate_no=167&display_group=1",
        "smsBody": "ACCORDION WALLET(WHITE/FREE) 구매 문의합니다.",
        "ordering": 109
      },
      {
        "id": "baby-sporty-tote-bag-lg",
        "name": "BABY SPORTY TOTE BAG",
        "color": "LIGHT GREY",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩138,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400BG020MLG.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4060&cate_no=70&display_group=1",
        "smsBody": "BABY SPORTY TOTE BAG(LIGHT GREY/FREE) 구매 문의합니다.",
        "ordering": 1
      },
      {
        "id": "classic-chain-quilting-mini-bag-iv",
        "name": "CLASSIC CHAIN QUILTING MINI BAG",
        "color": "IVORY",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩150,000",
        "discountPrice": "₩120,000",
        "image": "./images/Classic Chain Quilting Mini Bag.webp",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://kream.co.kr/products/281243?base_product_id=281242",
        "smsBody": "CLASSIC CHAIN QUILTING MINI BAG(IVORY/FREE) 구매 문의합니다.",
        "ordering": 2
      },
      {
        "id": "madeleine-round-bag-le",
        "name": "MADELEINE ROUND BAG",
        "color": "LIGHT BEIGE",
        "size": "FREE",
        "quantity": 3,
        "originalPrice": "₩158,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400BG057MLE.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4627&cate_no=70&display_group=1",
        "smsBody": "MADELEINE ROUND BAG(LIGHT BEIGE/FREE) 구매 문의합니다.",
        "ordering": 3
      },
      {
        "id": "madeleine-round-bag-pk",
        "name": "MADELEINE ROUND BAG",
        "color": "PINK",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩158,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400BG057M.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4629&cate_no=70&display_group=1",
        "smsBody": "MADELEINE ROUND BAG(PINK/FREE) 구매 문의합니다.",
        "ordering": 4
      },
      {
        "id": "madeleine-round-bag-lk",
        "name": "MADELEINE ROUND BAG",
        "color": "LIGHT KHAKI",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩158,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2400BG057MLK.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4628&cate_no=70&display_group=1",
        "smsBody": "MADELEINE ROUND BAG(LIGHT KHAKI/FREE) 구매 문의합니다.",
        "ordering": 5
      },
      {
        "id": "half-shirring-ribbon-round-bag-ch",
        "name": "HALF SHIRRING RIBBON ROUND BAG",
        "color": "CHARCOAL",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩157,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2500BG002VCH.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://kream.co.kr/products/430573?base_product_id=430573",
        "smsBody": "HALF SHIRRING RIBBON ROUND BAG(CHARCOAL/FREE) 구매 문의합니다.",
        "ordering": 6
      },
      {
        "id": "half-shirring-ribbon-round-bag-pk",
        "name": "HALF SHIRRING RIBBON ROUND BAG",
        "color": "PINK",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩138,000",
        "discountPrice": "₩120,000",
        "image": "./images/MK2411BG002MPK.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4978&cate_no=70&display_group=1",
        "smsBody": "HALF SHIRRING RIBBON ROUND BAG(PINK/FREE) 구매 문의합니다.",
        "ordering": 7
      },
      {
        "id": "faux-leather-seashell-bag-iv",
        "name": "FAUX LEATHER SEASHELL BAG",
        "color": "IVORY",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩289,000",
        "discountPrice": "₩170,000",
        "image": "./images/Matin Kim Faux Leather Seashell Bag Ivory.webp",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://kream.co.kr/products/249857?base_product_id=245550",
        "smsBody": "FAUX LEATHER SEASHELL BAG(IVORY/FREE) 구매 문의합니다.",
        "ordering": 8
      },
      {
        "id": "stud-leather-hobo-bag-bb",
        "name": "STUD LEATHER HOBO BAG",
        "color": "BLACK",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩298,000",
        "discountPrice": "₩268,200",
        "image": "./images/MK2477BG027MBB.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6004&cate_no=70&display_group=1",
        "smsBody": "STUD LEATHER HOBO BAG(BLACK/FREE) 구매 문의합니다.",
        "ordering": 9
      },
      {
        "id": "logo-cutted-crop-top-bb-m",
        "name": "LOGO CUTTED CROP TOP",
        "color": "BLACK",
        "size": "M",
        "quantity": 1,
        "originalPrice": "₩58,000",
        "discountPrice": "₩52,200",
        "image": "./images/MK2400TS002MBB.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4965&cate_no=27&display_group=1",
        "smsBody": "LOGO CUTTED CROP TOP(BLACK/M) 구매 문의합니다.",
        "ordering": 1019
      },
      {
        "id": "logo-cutted-crop-top-wh-s",
        "name": "LOGO CUTTED CROP TOP",
        "color": "WHITE",
        "size": "S",
        "quantity": 3,
        "originalPrice": "₩58,000",
        "discountPrice": "₩52,200",
        "image": "./images/MK2400TS002MWH.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4964&cate_no=27&display_group=1",
        "smsBody": "LOGO CUTTED CROP TOP(WHITE/S) 구매 문의합니다.",
        "ordering": 1020
      },
      {
        "id": "logo-cutted-layered-top-wh",
        "name": "LOGO CUTTED LAYERED TOP",
        "color": "WHITE",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩88,000",
        "discountPrice": "₩79,200",
        "image": "./images/MK2400TS003MWH.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4962&cate_no=27&display_group=1",
        "smsBody": "LOGO CUTTED LAYERED TOP(WHITE/FREE) 구매 문의합니다.",
        "ordering": 1021
      },
      {
        "id": "logo-crop-top-bb-m",
        "name": "LOGO CROP TOP",
        "color": "BLACK",
        "size": "M",
        "quantity": 1,
        "originalPrice": "₩39,000",
        "discountPrice": "₩35,100",
        "image": "./images/MK2400TS041MBB.jpeg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4132&cate_no=27&display_group=1",
        "smsBody": "LOGO CROP TOP(BLACK/M) 구매 문의합니다.",
        "ordering": 1022
      },
      {
        "id": "logo-crop-top-bb-s",
        "name": "LOGO CROP TOP",
        "color": "BLACK",
        "size": "S",
        "quantity": 3,
        "originalPrice": "₩39,000",
        "discountPrice": "₩35,100",
        "image": "./images/MK2400TS041MBB.jpeg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4132&cate_no=27&display_group=1",
        "smsBody": "LOGO CROP TOP(BLACK/S) 구매 문의합니다.",
        "ordering": 1023
      },
      {
        "id": "logo-crop-top-wh-s",
        "name": "LOGO CROP TOP",
        "color": "WHITE",
        "size": "S",
        "quantity": 4,
        "originalPrice": "₩39,000",
        "discountPrice": "₩35,100",
        "image": "./images/MK2400TS041MWH.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=4131&cate_no=27&display_group=1",
        "smsBody": "LOGO CROP TOP(WHITE/S) 구매 문의합니다.",
        "ordering": 1024
      },
      {
        "id": "logo-top-bb",
        "name": "LOGO TOP",
        "color": "BLACK",
        "size": "FREE",
        "quantity": 2,
        "originalPrice": "₩41,000",
        "discountPrice": "₩36,900",
        "image": "./images/MK2400TS042MBB.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=5319&cate_no=27&display_group=1",
        "smsBody": "LOGO TOP(BLACK/FREE) 구매 문의합니다.",
        "ordering": 1025
      },
      {
        "id": "volume-pocket-knit-zip-up-na-s",
        "name": "VOLUME POCKET KNIT ZIP UP",
        "color": "NAVY",
        "size": "S",
        "quantity": 2,
        "originalPrice": "₩198,000",
        "discountPrice": "₩170,000",
        "image": "./images/MK249OCD039M_NA_S.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6443&cate_no=26&display_group=1",
        "smsBody": "VOLUME POCKET KNIT ZIP UP(NAVY/S) 구매 문의합니다.",
        "ordering": 1026
      },
      {
        "id": "hairy-crochet-cardigan-for-men-br-l",
        "name": "HAIRY CROCHET CARDIGAN FOR MEN",
        "color": "BROWN",
        "size": "L",
        "quantity": 1,
        "originalPrice": "₩168,000",
        "discountPrice": "₩150,000",
        "image": "./images/MK2477CD536H_BR_L.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6163&cate_no=26&display_group=1",
        "smsBody": "HAIRY CROCHET CARDIGAN FOR MEN(BROWN/L) 구매 문의합니다.",
        "ordering": 1027
      },
      {
        "id": "color-line-point-logo-knit-pullover-gy-s",
        "name": "COLOR LINE POINT LOGO KNIT PULLOVER",
        "color": "GREY",
        "size": "S",
        "quantity": 1,
        "originalPrice": "₩148,000",
        "discountPrice": "₩130,000",
        "image": "./images/MK2477PO020M_GY_S.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6158&cate_no=27&display_group=1",
        "smsBody": "COLOR LINE POINT LOGO KNIT PULLOVER(GREY/S) 구매 문의합니다.",
        "ordering": 1028
      },
      {
        "id": "spell-point-stripe-knit-vest-bb-l",
        "name": "SPELL POINT STRIPE KNIT VEST",
        "color": "BLACK",
        "size": "L",
        "quantity": 2,
        "originalPrice": "₩148,000",
        "discountPrice": "₩130,000",
        "image": "./images/MK2400KV002M.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3682&cate_no=27&display_group=1",
        "smsBody": "SPELL POINT STRIPE KNIT VEST(BLACK/L) 구매 문의합니다.",
        "ordering": 1029
      },
      {
        "id": "spell-point-stripe-knit-vest-iv-l",
        "name": "SPELL POINT STRIPE KNIT VEST",
        "color": "IVORY",
        "size": "L",
        "quantity": 3,
        "originalPrice": "₩148,000",
        "discountPrice": "₩130,000",
        "image": "./images/MK2400KV002M_IV.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": false,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3681&cate_no=27&display_group=1",
        "smsBody": "SPELL POINT STRIPE KNIT VEST(IVORY/L) 구매 문의합니다.",
        "ordering": 1030
      },
      {
        "id": "spell-point-stripe-knit-vest-iv-m",
        "name": "SPELL POINT STRIPE KNIT VEST",
        "color": "IVORY",
        "size": "M",
        "quantity": 1,
        "originalPrice": "₩148,000",
        "discountPrice": "₩130,000",
        "image": "./images/MK2400KV002M_IV.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=3681&cate_no=27&display_group=1",
        "smsBody": "SPELL POINT STRIPE KNIT VEST(IVORY/M) 구매 문의합니다.",
        "ordering": 1031
      },
      {
        "id": "lightweight-padded-vest-jumper-for-women-bb",
        "name": "LIGHTWEIGHT PADDED VEST JUMPER FOR WOMEN",
        "color": "BLACK",
        "size": "FREE",
        "quantity": 1,
        "originalPrice": "₩188,000",
        "discountPrice": "₩160,000",
        "image": "./images/MK2477VT005M.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6181&cate_no=26&display_group=1",
        "smsBody": "LIGHTWEIGHT PADDED VEST JUMPER FOR WOMEN(BLACK/FREE) 구매 문의합니다.",
        "ordering": 1032
      },
      {
        "id": "knee-point-stripe-denim-pants-gy-m",
        "name": "KNEE POINT STRIPE DENIM PANTS",
        "color": "GREY",
        "size": "M",
        "quantity": 1,
        "originalPrice": "₩168,000",
        "discountPrice": "₩150,000",
        "image": "./images/MK2477DN028MGY.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6094&cate_no=28&display_group=1",
        "smsBody": "KNEE POINT STRIPE DENIM PANTS(GREY/M) 구매 문의합니다.",
        "ordering": 1033
      },
      {
        "id": "side-washed-denim-pants-bb-s",
        "name": "SIDE WASHED DENIM PANTS",
        "color": "BLACK",
        "size": "S",
        "quantity": 1,
        "originalPrice": "₩168,000",
        "discountPrice": "₩150,000",
        "image": "./images/MK2477DN034MBB.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6151&cate_no=28&display_group=1",
        "smsBody": "SIDE WASHED DENIM PANTS(BLACK/S) 구매 문의합니다.",
        "ordering": 1034
      },
      {
        "id": "oversize-belted-double-long-coat-ch-m",
        "name": "OVERSIZE BELTED DOUBLE LONG COAT",
        "color": "CHARCOAL",
        "size": "M",
        "quantity": 1,
        "originalPrice": "₩458,000",
        "discountPrice": "₩400,000",
        "image": "./images/MK249OCT005M_CH_M.jpg",
        "isSoldOut": false,
        "showSoldOutRibbon": true,
        "detailUrl": "https://matinkim.com/product/detail.html?product_no=6578&cate_no=26&display_group=1",
        "smsBody": "OVERSIZE BELTED DOUBLE LONG COAT(CHARCOAL/M) 구매 문의합니다.",
        "ordering": 1035
      }
    ]
}; 